### ISSUE TITLE
Adding already formatted text to chapters

### ISSUE THREAD

**Issue by PekopT** [Ae-Mc/FB2#1]
Hi @Ae-Mc ! 

First of all I need to say: Thank you for such a usefull package! It, literally, saved me a week of life =)

Thing, I suppose, might be usefull as a feature: 

I have some texts, that already formatted with html and I want to convert them to fb2
But there's no method that can just take such text as Element Tree, and for example, set it to Body.

What are you thinking about it ?

**Comment by Ae-Mc** [comment]
It's interesting idea. I will try to add it soon.
Do you have text divided into paragraphs?

**Comment by PekopT** [comment]
For example: https://www.dropbox.com/s/w7ofprdufu1p8o0/%D0%91%D0%B8%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F%20%D0%B3%D0%B5%D0%BD%D0%B5%D1%80%D0%B0%D0%BB%D0%B0%20%D0%9C%D0%B0%D1%80%D0%B1%D0%BE.tgz?dl=0

**Comment by Ae-Mc** [comment]
I add support for list of ET.Element to chapters.

**Comment by Nixellion** [comment]
Could you, please, provide an example of how to use this?

**Comment by Ae-Mc** [comment]
Sorry, I don't remember)
Looks like you can just use xml.etree.ElementTree as paragraph instead of str

**Comment by Nixellion** [comment]
Hello, yes, thanks, figured it out already, this works

```python
import xml.etree.ElementTree as ET
paragraph = ET.fromstring(str(html))
```

The rest is the same.
